networks:
  laravel_network:
    driver: bridge

volumes:
  db_server1_data:
    driver: local

services:
  db_server1:
    image: mysql:5.7
    container_name: db_server1
    restart: unless-stopped
    networks:
      - laravel_network
    volumes:
      - db_server1_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3308:3306"

  portfolio_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    networks:
      - laravel_network
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db_server1
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db_server1
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
